// Bubble Sort Implementation in C

// Less assume an array of integers and its size are given, let the size is 6...

// Index:-        0 | 1  | 2 | 3 | 4  | 5
// Values:-       7 | 11 | 9 | 2 | 17 | 4

// Sorted arr:-   2 | 4  | 7 | 9 | 11 | 17

// In this Algorithm, swap means, it will swap the values of two indexes if the first index value is greater than the second index value...

// Algorithm:-
// Index:-    0 | 1  | 2  | 3  | 4  | 5

// Pass 1:-   7 | 11 | 9  | 2  | 17 | 4     => checking index (0, 1) => if 7 > 11, then swap or else no swap => here, no swap...
//            7 | 9  | 11 | 2  | 17 | 4     => checking index (1, 2) => if 11 > 9, then swap or else no swap => here, swap...
//            7 | 9  | 2  | 11 | 17 | 4     => same for (2, 3) => swap...
//            7 | 9  | 2  | 11 | 17 | 4     => same for (3, 4) => no swap...
//            7 | 9  | 2  | 11 | 4  | 17    => same for (4, 5) => swap...
// After Pass 1, the largest value 17 is placed at the end of the array...

// Pass 2:-   7 | 9  | 2  | 11 | 4  | 17    => Now again checking from the start, check for (0, 1) => no swap...
//            7 | 2  | 9  | 11 | 4  | 17    => checking for (1, 2) => swap...
//            7 | 2  | 9  | 11 | 4  | 17    => same for (2, 3) => no swap...
//            7 | 2  | 9  | 4  | 11 | 17    => same for (3, 4) => swap...
// After Pass 2, the second largest value 11 is placed at the second last position of the array...

// Pass 3:-   2 | 7  | 9  | 4  | 11 | 17    => Now again checking from the start, check for (0, 1) => swap...
//            2 | 7  | 9  | 4  | 11 | 17    => checking for (1, 2) => no swap...
//            2 | 7  | 4  | 9  | 11 | 17    => same for (2, 3) => swap...
// After Pass 3, the third largest value 9 is placed at the third last position of the array...

// Pass 4:-   2 | 7  | 4  | 9  | 11 | 17    => Now again checking from the start, check for (0, 1) => no swap...
//            2 | 4  | 7  | 9  | 11 | 17    => checking for (1, 2) => no swap...
// After Pass 4, the fourth largest value 7 is placed at the fourth last position of the array...

// Pass 5:-   2 | 7  | 4  | 9  | 11 | 17    => Now again checking from the start, check for (0, 1) => no swap...
// After Pass 5, the fifth largest value 4 is placed at the fifth last position of the array...

// After all these passes, the array is sorted...

// we need n-1 passes to sort n elements... and in each pass, we need to do comparisons for n-i-1 times where i is the current pass number...
// So there are total 1 + 2 + 3 + ... + (n-1) = n(n-1)/2 comparisons in total... which is O(n^2) time complexity... best case is O(n) when the array is already sorted...
// Bubble Sort is a stable sort... For example,{7,6,1,6'}=>{6,7,1,6'}=>{6,6',1,7}=>{1,6,6',7}=> Here 6 and 6' maintains their relative position...
// Space Complexity is O(1) as we are not using any extra space except some variables...
// It is an in-place sorting algorithm...
// It is not a recursive algorithm...
// It is not by defualt adaptive in nature, but we can make it adaptive in nature... by editing the code a bit... on first pass, if no swap occurs, then the array is already sorted...

#include<stdio.h>

void printArr(int* arr, int n) {
    for (int i = 0; i < n; i++) {
        printf("%d ", arr[i]);
    }
    printf("\n");
}

void bubbleSort(int* arr, int n) {
    int isSorted = 0;
    for (int i = 0; i < n-1; i++) {   // for n-1 passes
        printf("Pass %d\n", i+1);   // This line is just to show how many passes have been made
        isSorted = 1;
        for (int j = 0; j < n-i-1; j++) {   // for n-i-1 comparisons in each pass
            if (arr[j] > arr[j+1]){    // swap if the element found is greater than the next element
                int temp = arr[j];
                arr[j] = arr[j+1];
                arr[j+1] = temp;
                isSorted = 0;
            }
        }
        if (isSorted) {   // If no two elements were swapped by inner loop, then break --> to make it adaptive
            return;
        }
    } 
}

int main() {
    // int arr[] = {7, 11, 9, 2, 17, 4};
    int arr[] = {1, 2, 3, 4, 5, 6};
    int n = sizeof(arr)/sizeof(arr[0]);

    printf("Original arr: ");
    printArr(arr, n);

    bubbleSort(arr, n);

    printf("Sorted array: ");
    printArr(arr, n);
    
    return 0;
}